### ISSUE TITLE
ant release fails

### ISSUE THREAD

**Issue by arunisaac** [onyxbits/photobookmark#1]
```
ant release
```

fails with

```
BUILD FAILED
/home/myuser/de.onyxbits.photobookmark/custom_rules.xml:19: Warning: Could not find file /home/myuser/de.onyxbits.photobookmark/bin/de.onyxbits.photobookmark-release.apk to copy.
```

Is the post-build copy segment in custom_rules.xml required? Removing it solves the problem.

**Comment by onyxbits** [comment]
Hi,
the custom_rules.xml is not required. All it does is some file copying
after building so the version number shows up in the filename. Handy for
my purposes, but if it causes you any trouble, you can simply delete the
file as a whole.

Am Freitag, den 09.05.2014, 04:38 -0700 schrieb arunisaac:

**Comment by arunisaac** [comment]
Very well, then. I'll delete it. Thanks!
