### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arunisaac** [onyxbits/photobookmark#2]
I'm working on including the app in F-Droid

https://f-droid.org/

For that, I would like to know what license this app is released under.

**Comment by onyxbits** [comment]
Am Montag, den 12.05.2014, 16:13 -0700 schrieb arunisaac:

> I'm working on including the app in F-Droid
> 
> https://f-droid.org/
> 
> For that, I would like to know what license this app is released
> under.
> 
> —
> Reply to this email directly or view it on GitHub.

Uhm ... APL2 ... as stated in the LICENSE file?

**Comment by arunisaac** [comment]
Yup... Should have looked there... My bad...
Thanks...
